### ISSUE TITLE
"ADD" command in Dockerfile doesn't copy the file when building an image using "decking build all"

### ISSUE THREAD

**Issue by ghost** [makeusabrew/decking-example#6]
I have following hierarchy 

```
docker/ 
    ---> decking.yaml
    ---> eureka/
        ---> Dockerfile
        ---> eureka.jar
```

and the files content:

decking.yaml

```
 images:
    "user/eureka": "./eureka"
containers:
    eureka:
        image:  user/eureka  
        port: ["8761:8761"]
clusters:
     dev:  ["eureka"]
```

Dockerfile

```
FROM user/java
EXPOSE 8761
ADD eureka.jar /opt/eureka.jar
CMD ["java -jar /opt/eureka.jar"]
```

when I run "sudo decking build all" the run stops on step 2 and the image is not built. Output:

```
Looking up build data for user/eureka
Building image user/eureka from ./eureka/Dockerfile
Uploading compressed context...
Step 0 : FROM user/java
 ---> db15bac74b89
Step 1 : EXPOSE 8761
 ---> Using cache
 ---> 42b783b09a9d
Step 2 : ADD eureka.jar /opt/eureka.jar
```

docker log file say:

```
INFO[350126] POST /build?t=user%2Feureka                  
INFO[350126] +job build()                                 
eureka.jar: no such file or directory
INFO[350127] -job build() = ERR (1)          
```

but when I run "sudo docker build ." on this Dockerfile all works fine no error there. Output:

```
Step 0 : FROM user/java
 ---> db15bac74b89
Step 1 : EXPOSE 8761
 ---> Using cache
 ---> 42b783b09a9d
Step 2 : ADD eureka.jar /opt/eureka.jar
 ---> Using cache
 ---> 4849ffd20be8
Step 3 : CMD java -jar /opt/eureka.jar
 ---> Using cache
 ---> c24c0bccc231
Successfully built c24c0bccc231
```

and docker log:

```
INFO[350426] POST /v1.16/build?rm=1&t=user%2Feureka       
INFO[350426] +job build()                                 
INFO[350426] -job build() = OK (0)   
```

some info from "sudo docker version"

```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

**Comment by makeusabrew** [comment]
Hi!

First of all I'd recommend adding your user(s) to the `docker` group; that way you can avoid running docker and decking with sudo: http://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo

To your issue: decking runs the Dockerfile as if it was in the same directory as your decking.yaml file. As such your Dockerfile will want to `ADD ./eureka/eureka.jar /opt/eureka.jar` instead.

Writing this makes me realise this behaviour is not obvious, even though it's in there for good reason (basically to make sure the Dockerfile has access to the full context of your project). Will try and get something clear about it in the docs.

**Comment by ghost** [comment]
Thank you this works just fine.
